### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Fightingzzy** [koolo233/Baseline4SolvingRBConvection#1]
Hello, master. Could you please provide the test.csv file for Rayleigh–Bénard Convection?

**Comment by ZijiangY1116** [comment]
I have organized and uploaded the dataset (including the test dataset and the ground truth) to Kaggle: [Solve PDEs with AI | Rayleigh–Bénard Convection](https://www.kaggle.com/datasets/zijiangyang1116/solve-pdes-with-ai-rayleighbnard-convection/data)

**Comment by Fightingzzy** [comment]
Your help is much appreciated, sir. Thank you for your kind assistance.
